### PR TITLE
Install mercurial through pip - more control over version

### PR DESCRIPTION
**Pull request by sysarcher**
- Change from installing using apt (which can lead to old versions) to installing using `pip`. 
- Add `defaults/main.yml` file where version number can be configured

### CODE REVIEW

**Comment by hectcastro** [comment]
Hey @shrmrf, thanks for the contribution. I think a more generic installation method via `pip` makes sense.

While testing this PR using the example Vagrant project tracked in the repository, the step for installing Mercurial fails because the Python development package isn't installed:

```
TASK [azavea.mercurial : Install Mercurial] ************************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip install mercurial==3.9.2", "failed": true, "msg": "stdout: Downloading/unpacking mercurial==3.9.2\n  Running setup.py (path:/tmp/pip_build_root/mercurial/setup.py) egg_info for package mercurial\n    \n    Python headers are required to build Mercurial but weren't found in /usr/include/python2.7/Python.h\n    Complete output from command python setup.py egg_info:\n    running egg_info\n\ncreating pip-egg-info/mercurial.egg-info\n\nwriting pip-egg-info/mercurial.egg-info/PKG-INFO\n\nwriting top-level names to pip-egg-info/mercurial.egg-info/top_level.txt\n\nwriting dependency_links to pip-egg-info/mercurial.egg-info/dependency_links.txt\n\nwriting manifest file 'pip-egg-info/mercurial.egg-info/SOURCES.txt'\n\nwarning: manifest_maker: standard file '-c' not found\n\n\n\nPython headers are required to build Mercurial but weren't found in /usr/include/python2.7/Python.h\n\n----------------------------------------\nCleaning up...\nCommand python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/mercurial\nStoring debug log for failure in /root/.pip/pip.log\n"}
```

We have two roles that can help in ensuring that Python and `pip` are both installed:
- https://github.com/azavea/ansible-pip
- https://github.com/azavea/ansible-python (with `python_development` set to `True`)

Would you mind incorporating those into this PR so that this role can install Mercurial cleanly in isolation? The [`ansible-docker`](https://github.com/azavea/ansible-docker) provides a good example of how to integrate dependent roles.

**Comment by sysarcher** [comment]
Hey  @hectcastro thanks for the feedback. Yeah, I guess I just went for the quick-and-dirty stuff. I'll add the missing roles as dependencies and make a `requirements.yml` file in the `examples` directory.

I didn't test the role in isolation 👎  Will do so tonight.

Thanks!

**Comment by sysarcher** [comment]
Hello @hectcastro I changed and tested (on Digital Ocean - didn't have Vagrant handy) the roles. These should be more azaveaic.

**Comment by sysarcher** [comment]
BTW, since you're using `apt` for packages, why don't you get rid of ubuntu-specific stuff in https://github.com/azavea/ansible-python/blob/develop/tasks/main.yml#L3 ?

It just prevents the role from running on Debian OS. In face, I'm of the opinion, that we shouldn't force the version and let python default version be installed. What do you think? Is it pull-request worthy?

Similarly, I removed `pip_version` from here https://github.com/azavea/ansible-pip/blob/develop/tasks/main.yml#L3 (for my case) since, we can go with what is provided by default by the package manager. If there is a specific version that the user wants installed, maybe we can do `pip install pip==1.5.*` in a second step? I'd say its very safe to go with the package manager's version.

**Comment by hectcastro** [comment]
> BTW, since you're using apt for packages, why don't you get rid of ubuntu-specific stuff in https://github.com/azavea/ansible-python/blob/develop/tasks/main.yml#L3 ?
> 
> It just prevents the role from running on Debian OS. In face, I'm of the opinion, that we shouldn't force the version and let python default version be installed. What do you think? Is it pull-request worthy?

I don't think it blocks Debian usage, just that a Debian user will have to override the `python_version` variable to whatever the package version is.

> Similarly, I removed pip_version from here https://github.com/azavea/ansible-pip/blob/develop/tasks/main.yml#L3 (for my case) since, we can go with what is provided by default by the package manager. If there is a specific version that the user wants installed, maybe we can do pip install pip==1.5.\* in a second step? I'd say its very safe to go with the package manager's version.

In general, we pin versions of packages to ensure that dependencies aren't changing on us across deployments. Generally, the most up-to-date version of a package will work well with other packages on the OS, but in some cases it won't play well with an application we're trying to deploy on top of the OS. In those cases, the version pinning helps us learn about dependency changes early on in the deployment process vs. after it's too late.

**Review by hectcastro — APPROVED** [review]
👍

**Comment by sysarcher** [comment]
Hey @hectcastro thanks for approving the pull request. Hmmm... I still think that the package-manager's versions of `pip` and `python-dev` are the way to go but its your call (of course). I will change this in my fork because that's how we'd use it at our company.

**Pull request merged**
